SET DEFINE OFF;

PROMPT ============================================
PROMPT College Quiz Management System - Step 1
PROMPT Oracle SQL*Plus Schema + PL/SQL + Triggers + Test Data
PROMPT ============================================

PROMPT Dropping views...
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_STUDENT_PUBLISHED_RESULTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_TEACHER_SUBMISSIONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_TEACHER_QUIZ_DASHBOARD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT Dropping triggers...
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_BI_DEPARTMENT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_BI_TEACHER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_BI_STUDENT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_BI_SUBJECT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_BI_QUIZ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_BI_QUESTION'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_BI_QUESTION_OPTION'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_BI_QUIZ_ATTEMPT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_BI_STUDENT_ANSWER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_BI_RESULT_PUBLISH_LOG'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_BI_ANSWER_AUTOSAVE_LOG'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_BIU_TEACHER_VALIDATE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_BIU_STUDENT_VALIDATE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_BIU_STUDENT_ANSWER_VALIDATE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_AIUD_STUDENT_ANSWER_AUTOSAVE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_QUESTION_TOTALS_CT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT Dropping packages and functions...
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE PKG_QUIZ_ADMIN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE PKG_QUIZ_ATTEMPT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_IS_CORRECT_OPTION'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT Dropping sequences...
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DEPARTMENT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TEACHER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_STUDENT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SUBJECT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_QUIZ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_QUESTION'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_QUESTION_OPTION'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_QUIZ_ATTEMPT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_STUDENT_ANSWER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RESULT_PUBLISH_LOG'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ANSWER_AUTOSAVE_LOG'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT Dropping tables...
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ANSWER_AUTOSAVE_LOG CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RESULT_PUBLISH_LOG CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE STUDENT_ANSWER CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE QUIZ_ATTEMPT CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE QUESTION_OPTION CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE QUESTION CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE QUIZ CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SUBJECT CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE STUDENT CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TEACHER CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DEPARTMENT CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT Creating tables...
CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID    NUMBER(10)     NOT NULL,
    DEPARTMENT_NAME  VARCHAR2(100)  NOT NULL,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT UQ_DEPARTMENT_NAME UNIQUE (DEPARTMENT_NAME),
    CONSTRAINT CHK_DEPARTMENT_NAME_NN CHECK (TRIM(DEPARTMENT_NAME) IS NOT NULL)
);

CREATE TABLE TEACHER (
    TEACHER_ID       NUMBER(10)     NOT NULL,
    TEACHER_CODE     VARCHAR2(20)   NOT NULL,
    NAME             VARCHAR2(100)  NOT NULL,
    PASSWORD         VARCHAR2(100)  NOT NULL,
    DEPARTMENT_ID    NUMBER(10)     NOT NULL,
    CONSTRAINT PK_TEACHER PRIMARY KEY (TEACHER_ID),
    CONSTRAINT UQ_TEACHER_CODE UNIQUE (TEACHER_CODE),
    CONSTRAINT FK_TEACHER_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT (DEPARTMENT_ID),
    CONSTRAINT CHK_TEACHER_NAME_NN CHECK (TRIM(NAME) IS NOT NULL),
    CONSTRAINT CHK_TEACHER_CODE_NN CHECK (TRIM(TEACHER_CODE) IS NOT NULL),
    CONSTRAINT CHK_TEACHER_PASSWORD_NN CHECK (TRIM(PASSWORD) IS NOT NULL)
);

CREATE TABLE STUDENT (
    STUDENT_ID         NUMBER(10)     NOT NULL,
    REGISTRATION_NO    CHAR(9)        NOT NULL,
    NAME               VARCHAR2(100)  NOT NULL,
    PASSWORD           VARCHAR2(100)  NOT NULL,
    DEPARTMENT_ID      NUMBER(10)     NOT NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY (STUDENT_ID),
    CONSTRAINT UQ_STUDENT_REGISTRATION_NO UNIQUE (REGISTRATION_NO),
    CONSTRAINT FK_STUDENT_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT (DEPARTMENT_ID),
    CONSTRAINT CHK_STUDENT_NAME_NN CHECK (TRIM(NAME) IS NOT NULL),
    CONSTRAINT CHK_STUDENT_PASSWORD_NN CHECK (TRIM(PASSWORD) IS NOT NULL),
    CONSTRAINT CHK_STUDENT_REG_NO CHECK (REGEXP_LIKE(REGISTRATION_NO, '^[0-9]{9}$'))
);

CREATE TABLE SUBJECT (
    SUBJECT_ID        NUMBER(10)     NOT NULL,
    SUBJECT_NAME      VARCHAR2(120)  NOT NULL,
    SUBJECT_CODE      VARCHAR2(20)   NOT NULL,
    SEMESTER          NUMBER(2)      NOT NULL,
    DEPARTMENT_ID     NUMBER(10)     NOT NULL,
    CONSTRAINT PK_SUBJECT PRIMARY KEY (SUBJECT_ID),
    CONSTRAINT UQ_SUBJECT_CODE UNIQUE (SUBJECT_CODE),
    CONSTRAINT UQ_SUBJECT_NAME_DEPT_SEM UNIQUE (SUBJECT_NAME, DEPARTMENT_ID, SEMESTER),
    CONSTRAINT FK_SUBJECT_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT (DEPARTMENT_ID),
    CONSTRAINT CHK_SUBJECT_NAME_NN CHECK (TRIM(SUBJECT_NAME) IS NOT NULL),
    CONSTRAINT CHK_SUBJECT_CODE_NN CHECK (TRIM(SUBJECT_CODE) IS NOT NULL),
    CONSTRAINT CHK_SUBJECT_SEMESTER CHECK (SEMESTER BETWEEN 1 AND 8)
);

CREATE TABLE QUIZ (
    QUIZ_ID             NUMBER(10)     NOT NULL,
    QUIZ_TITLE          VARCHAR2(200)  NOT NULL,
    DURATION_MINUTES    NUMBER(4)      NOT NULL,
    TOTAL_MARKS         NUMBER(8,2)    DEFAULT 0 NOT NULL,
    QUIZ_DATE           DATE           NOT NULL,
    RESULTS_PUBLISHED   CHAR(1)        DEFAULT 'N' NOT NULL,
    SUBJECT_ID          NUMBER(10)     NOT NULL,
    CREATED_BY          NUMBER(10)     NOT NULL,
    CONSTRAINT PK_QUIZ PRIMARY KEY (QUIZ_ID),
    CONSTRAINT FK_QUIZ_SUBJECT FOREIGN KEY (SUBJECT_ID)
        REFERENCES SUBJECT (SUBJECT_ID),
    CONSTRAINT FK_QUIZ_TEACHER FOREIGN KEY (CREATED_BY)
        REFERENCES TEACHER (TEACHER_ID),
    CONSTRAINT CHK_QUIZ_TITLE_NN CHECK (TRIM(QUIZ_TITLE) IS NOT NULL),
    CONSTRAINT CHK_QUIZ_DURATION CHECK (DURATION_MINUTES BETWEEN 1 AND 300),
    CONSTRAINT CHK_QUIZ_TOTAL_MARKS CHECK (TOTAL_MARKS >= 0),
    CONSTRAINT CHK_QUIZ_RESULTS_PUBLISHED CHECK (RESULTS_PUBLISHED IN ('Y', 'N'))
);

CREATE TABLE QUESTION (
    QUESTION_ID       NUMBER(10)      NOT NULL,
    QUESTION_TEXT     VARCHAR2(1000)  NOT NULL,
    QUESTION_TYPE     VARCHAR2(10)    DEFAULT 'SCQ' NOT NULL,
    MARKS             NUMBER(6,2)     NOT NULL,
    QUIZ_ID           NUMBER(10)      NOT NULL,
    DISPLAY_ORDER     NUMBER(4)       NOT NULL,
    CONSTRAINT PK_QUESTION PRIMARY KEY (QUESTION_ID),
    CONSTRAINT FK_QUESTION_QUIZ FOREIGN KEY (QUIZ_ID)
        REFERENCES QUIZ (QUIZ_ID),
    CONSTRAINT UQ_QUESTION_QUIZ_ORDER UNIQUE (QUIZ_ID, DISPLAY_ORDER),
    CONSTRAINT CHK_QUESTION_TEXT_NN CHECK (TRIM(QUESTION_TEXT) IS NOT NULL),
    CONSTRAINT CHK_QUESTION_TYPE CHECK (QUESTION_TYPE = 'SCQ'),
    CONSTRAINT CHK_QUESTION_MARKS CHECK (MARKS > 0),
    CONSTRAINT CHK_QUESTION_DISPLAY_ORDER CHECK (DISPLAY_ORDER > 0)
);

CREATE TABLE QUESTION_OPTION (
    OPTION_ID             NUMBER(10)      NOT NULL,
    OPTION_TEXT           VARCHAR2(500)   NOT NULL,
    IS_CORRECT            CHAR(1)         DEFAULT 'N' NOT NULL,
    QUESTION_ID           NUMBER(10)      NOT NULL,
    DISPLAY_ORDER         NUMBER(4)       NOT NULL,
    CORRECT_QUESTION_ID   NUMBER(10)
        GENERATED ALWAYS AS (CASE WHEN IS_CORRECT = 'Y' THEN QUESTION_ID END) VIRTUAL,
    CONSTRAINT PK_QUESTION_OPTION PRIMARY KEY (OPTION_ID),
    CONSTRAINT FK_QUESTION_OPTION_QUESTION FOREIGN KEY (QUESTION_ID)
        REFERENCES QUESTION (QUESTION_ID),
    CONSTRAINT UQ_QUESTION_OPTION_TEXT UNIQUE (QUESTION_ID, OPTION_TEXT),
    CONSTRAINT UQ_QUESTION_OPTION_ORDER UNIQUE (QUESTION_ID, DISPLAY_ORDER),
    CONSTRAINT UQ_QUESTION_OPTION_ONE_CORRECT UNIQUE (CORRECT_QUESTION_ID),
    CONSTRAINT CHK_QUESTION_OPTION_TEXT_NN CHECK (TRIM(OPTION_TEXT) IS NOT NULL),
    CONSTRAINT CHK_QUESTION_OPTION_CORRECT CHECK (IS_CORRECT IN ('Y', 'N')),
    CONSTRAINT CHK_QUESTION_OPTION_ORDER CHECK (DISPLAY_ORDER > 0)
);

CREATE TABLE QUIZ_ATTEMPT (
    ATTEMPT_ID          NUMBER(10)      NOT NULL,
    SUBMISSION_TIME     DATE,
    TOTAL_SCORE         NUMBER(8,2)     DEFAULT 0 NOT NULL,
    QUIZ_ID             NUMBER(10)      NOT NULL,
    STUDENT_ID          NUMBER(10)      NOT NULL,
    START_TIME          DATE            DEFAULT SYSDATE NOT NULL,
    LAST_SAVED_AT       DATE            DEFAULT SYSDATE NOT NULL,
    STATUS              VARCHAR2(20)    DEFAULT 'IN_PROGRESS' NOT NULL,
    CONSTRAINT PK_QUIZ_ATTEMPT PRIMARY KEY (ATTEMPT_ID),
    CONSTRAINT UQ_QUIZ_ATTEMPT_QUIZ_STUDENT UNIQUE (QUIZ_ID, STUDENT_ID),
    CONSTRAINT FK_QUIZ_ATTEMPT_QUIZ FOREIGN KEY (QUIZ_ID)
        REFERENCES QUIZ (QUIZ_ID),
    CONSTRAINT FK_QUIZ_ATTEMPT_STUDENT FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT (STUDENT_ID),
    CONSTRAINT CHK_QUIZ_ATTEMPT_SCORE CHECK (TOTAL_SCORE >= 0),
    CONSTRAINT CHK_QUIZ_ATTEMPT_STATUS CHECK (STATUS IN ('IN_PROGRESS', 'SUBMITTED', 'AUTO_SUBMITTED')),
    CONSTRAINT CHK_QUIZ_ATTEMPT_SUBMISSION CHECK (
        (STATUS = 'IN_PROGRESS' AND SUBMISSION_TIME IS NULL) OR
        (STATUS IN ('SUBMITTED', 'AUTO_SUBMITTED') AND SUBMISSION_TIME IS NOT NULL)
    )
);

CREATE TABLE STUDENT_ANSWER (
    ANSWER_ID             NUMBER(10)    NOT NULL,
    IS_CORRECT            CHAR(1)       DEFAULT 'N' NOT NULL,
    ATTEMPT_ID            NUMBER(10)    NOT NULL,
    QUESTION_ID           NUMBER(10)    NOT NULL,
    SELECTED_OPTION_ID    NUMBER(10),
    LAST_UPDATED_AT       DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_STUDENT_ANSWER PRIMARY KEY (ANSWER_ID),
    CONSTRAINT UQ_STUDENT_ANSWER_ATTEMPT_Q UNIQUE (ATTEMPT_ID, QUESTION_ID),
    CONSTRAINT FK_STUDENT_ANSWER_ATTEMPT FOREIGN KEY (ATTEMPT_ID)
        REFERENCES QUIZ_ATTEMPT (ATTEMPT_ID),
    CONSTRAINT FK_STUDENT_ANSWER_QUESTION FOREIGN KEY (QUESTION_ID)
        REFERENCES QUESTION (QUESTION_ID),
    CONSTRAINT FK_STUDENT_ANSWER_OPTION FOREIGN KEY (SELECTED_OPTION_ID)
        REFERENCES QUESTION_OPTION (OPTION_ID),
    CONSTRAINT CHK_STUDENT_ANSWER_CORRECT CHECK (IS_CORRECT IN ('Y', 'N'))
);

CREATE TABLE RESULT_PUBLISH_LOG (
    PUBLISH_LOG_ID      NUMBER(10)    NOT NULL,
    QUIZ_ID             NUMBER(10)    NOT NULL,
    PUBLISHED_BY        NUMBER(10)    NOT NULL,
    PUBLISHED_AT        DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RESULT_PUBLISH_LOG PRIMARY KEY (PUBLISH_LOG_ID),
    CONSTRAINT FK_RPL_QUIZ FOREIGN KEY (QUIZ_ID)
        REFERENCES QUIZ (QUIZ_ID),
    CONSTRAINT FK_RPL_TEACHER FOREIGN KEY (PUBLISHED_BY)
        REFERENCES TEACHER (TEACHER_ID)
);

CREATE TABLE ANSWER_AUTOSAVE_LOG (
    AUTOSAVE_LOG_ID     NUMBER(10)     NOT NULL,
    ANSWER_ID           NUMBER(10)     NOT NULL,
    ATTEMPT_ID          NUMBER(10)     NOT NULL,
    QUESTION_ID         NUMBER(10)     NOT NULL,
    OPERATION_TYPE      VARCHAR2(10)   NOT NULL,
    SAVED_AT            DATE           DEFAULT SYSDATE NOT NULL,
    SAVED_BY_DB_USER    VARCHAR2(128)  DEFAULT USER NOT NULL,
    CONSTRAINT PK_ANSWER_AUTOSAVE_LOG PRIMARY KEY (AUTOSAVE_LOG_ID),
    CONSTRAINT FK_AAL_ANSWER FOREIGN KEY (ANSWER_ID)
        REFERENCES STUDENT_ANSWER (ANSWER_ID),
    CONSTRAINT FK_AAL_ATTEMPT FOREIGN KEY (ATTEMPT_ID)
        REFERENCES QUIZ_ATTEMPT (ATTEMPT_ID),
    CONSTRAINT FK_AAL_QUESTION FOREIGN KEY (QUESTION_ID)
        REFERENCES QUESTION (QUESTION_ID),
    CONSTRAINT CHK_AAL_OPERATION_TYPE CHECK (OPERATION_TYPE IN ('INSERT', 'UPDATE', 'DELETE'))
);

PROMPT Creating sequences...
CREATE SEQUENCE SEQ_DEPARTMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TEACHER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_STUDENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SUBJECT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_QUIZ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_QUESTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_QUESTION_OPTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_QUIZ_ATTEMPT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_STUDENT_ANSWER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_RESULT_PUBLISH_LOG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ANSWER_AUTOSAVE_LOG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

PROMPT Creating utility function...
CREATE OR REPLACE FUNCTION FN_IS_CORRECT_OPTION (
    P_OPTION_ID IN QUESTION_OPTION.OPTION_ID%TYPE
) RETURN NUMBER
IS
    V_IS_CORRECT QUESTION_OPTION.IS_CORRECT%TYPE;
BEGIN
    SELECT IS_CORRECT
      INTO V_IS_CORRECT
      FROM QUESTION_OPTION
     WHERE OPTION_ID = P_OPTION_ID;

    RETURN CASE WHEN V_IS_CORRECT = 'Y' THEN 1 ELSE 0 END;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

PROMPT Creating key-generation triggers...
CREATE OR REPLACE TRIGGER TRG_BI_DEPARTMENT
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN
    IF :NEW.DEPARTMENT_ID IS NULL THEN
        :NEW.DEPARTMENT_ID := SEQ_DEPARTMENT.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_TEACHER
BEFORE INSERT ON TEACHER
FOR EACH ROW
BEGIN
    IF :NEW.TEACHER_ID IS NULL THEN
        :NEW.TEACHER_ID := SEQ_TEACHER.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_STUDENT
BEFORE INSERT ON STUDENT
FOR EACH ROW
BEGIN
    IF :NEW.STUDENT_ID IS NULL THEN
        :NEW.STUDENT_ID := SEQ_STUDENT.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_SUBJECT
BEFORE INSERT ON SUBJECT
FOR EACH ROW
BEGIN
    IF :NEW.SUBJECT_ID IS NULL THEN
        :NEW.SUBJECT_ID := SEQ_SUBJECT.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_QUIZ
BEFORE INSERT ON QUIZ
FOR EACH ROW
BEGIN
    IF :NEW.QUIZ_ID IS NULL THEN
        :NEW.QUIZ_ID := SEQ_QUIZ.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_QUESTION
BEFORE INSERT ON QUESTION
FOR EACH ROW
BEGIN
    IF :NEW.QUESTION_ID IS NULL THEN
        :NEW.QUESTION_ID := SEQ_QUESTION.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_QUESTION_OPTION
BEFORE INSERT ON QUESTION_OPTION
FOR EACH ROW
BEGIN
    IF :NEW.OPTION_ID IS NULL THEN
        :NEW.OPTION_ID := SEQ_QUESTION_OPTION.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_QUIZ_ATTEMPT
BEFORE INSERT ON QUIZ_ATTEMPT
FOR EACH ROW
BEGIN
    IF :NEW.ATTEMPT_ID IS NULL THEN
        :NEW.ATTEMPT_ID := SEQ_QUIZ_ATTEMPT.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_STUDENT_ANSWER
BEFORE INSERT ON STUDENT_ANSWER
FOR EACH ROW
BEGIN
    IF :NEW.ANSWER_ID IS NULL THEN
        :NEW.ANSWER_ID := SEQ_STUDENT_ANSWER.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_RESULT_PUBLISH_LOG
BEFORE INSERT ON RESULT_PUBLISH_LOG
FOR EACH ROW
BEGIN
    IF :NEW.PUBLISH_LOG_ID IS NULL THEN
        :NEW.PUBLISH_LOG_ID := SEQ_RESULT_PUBLISH_LOG.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_ANSWER_AUTOSAVE_LOG
BEFORE INSERT ON ANSWER_AUTOSAVE_LOG
FOR EACH ROW
BEGIN
    IF :NEW.AUTOSAVE_LOG_ID IS NULL THEN
        :NEW.AUTOSAVE_LOG_ID := SEQ_ANSWER_AUTOSAVE_LOG.NEXTVAL;
    END IF;
END;
/

PROMPT Creating validation triggers...
CREATE OR REPLACE TRIGGER TRG_BIU_TEACHER_VALIDATE
BEFORE INSERT OR UPDATE ON TEACHER
FOR EACH ROW
BEGIN
    IF NOT REGEXP_LIKE(:NEW.NAME, '^[A-Za-z][A-Za-z .''-]*$') THEN
        RAISE_APPLICATION_ERROR(-20001, 'Teacher name must contain only alphabets and basic punctuation.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_STUDENT_VALIDATE
BEFORE INSERT OR UPDATE ON STUDENT
FOR EACH ROW
BEGIN
    IF NOT REGEXP_LIKE(:NEW.NAME, '^[A-Za-z][A-Za-z .''-]*$') THEN
        RAISE_APPLICATION_ERROR(-20002, 'Student name must contain only alphabets and basic punctuation.');
    END IF;

    IF NOT REGEXP_LIKE(:NEW.REGISTRATION_NO, '^[0-9]{9}$') THEN
        RAISE_APPLICATION_ERROR(-20003, 'Registration number must be exactly 9 digits.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_STUDENT_ANSWER_VALIDATE
BEFORE INSERT OR UPDATE ON STUDENT_ANSWER
FOR EACH ROW
DECLARE
    V_ATTEMPT_QUIZ_ID   QUIZ_ATTEMPT.QUIZ_ID%TYPE;
    V_QUESTION_QUIZ_ID  QUESTION.QUIZ_ID%TYPE;
    V_OPTION_QUESTION   QUESTION_OPTION.QUESTION_ID%TYPE;
BEGIN
    SELECT QUIZ_ID
      INTO V_ATTEMPT_QUIZ_ID
      FROM QUIZ_ATTEMPT
     WHERE ATTEMPT_ID = :NEW.ATTEMPT_ID;

    SELECT QUIZ_ID
      INTO V_QUESTION_QUIZ_ID
      FROM QUESTION
     WHERE QUESTION_ID = :NEW.QUESTION_ID;

    IF V_ATTEMPT_QUIZ_ID <> V_QUESTION_QUIZ_ID THEN
        RAISE_APPLICATION_ERROR(-20004, 'Answered question does not belong to the attempted quiz.');
    END IF;

    IF :NEW.SELECTED_OPTION_ID IS NOT NULL THEN
        SELECT QUESTION_ID
          INTO V_OPTION_QUESTION
          FROM QUESTION_OPTION
         WHERE OPTION_ID = :NEW.SELECTED_OPTION_ID;

        IF V_OPTION_QUESTION <> :NEW.QUESTION_ID THEN
            RAISE_APPLICATION_ERROR(-20005, 'Selected option does not belong to the answered question.');
        END IF;
    END IF;

    :NEW.LAST_UPDATED_AT := SYSDATE;
END;
/

PROMPT Creating autosave and derived-total triggers...
CREATE OR REPLACE TRIGGER TRG_AIUD_STUDENT_ANSWER_AUTOSAVE
AFTER INSERT OR UPDATE OR DELETE ON STUDENT_ANSWER
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE QUIZ_ATTEMPT
           SET LAST_SAVED_AT = SYSDATE
         WHERE ATTEMPT_ID = :NEW.ATTEMPT_ID;

        INSERT INTO ANSWER_AUTOSAVE_LOG (ANSWER_ID, ATTEMPT_ID, QUESTION_ID, OPERATION_TYPE)
        VALUES (:NEW.ANSWER_ID, :NEW.ATTEMPT_ID, :NEW.QUESTION_ID, 'INSERT');
    ELSIF UPDATING THEN
        UPDATE QUIZ_ATTEMPT
           SET LAST_SAVED_AT = SYSDATE
         WHERE ATTEMPT_ID = :NEW.ATTEMPT_ID;

        INSERT INTO ANSWER_AUTOSAVE_LOG (ANSWER_ID, ATTEMPT_ID, QUESTION_ID, OPERATION_TYPE)
        VALUES (:NEW.ANSWER_ID, :NEW.ATTEMPT_ID, :NEW.QUESTION_ID, 'UPDATE');
    ELSE
        UPDATE QUIZ_ATTEMPT
           SET LAST_SAVED_AT = SYSDATE
         WHERE ATTEMPT_ID = :OLD.ATTEMPT_ID;

        INSERT INTO ANSWER_AUTOSAVE_LOG (ANSWER_ID, ATTEMPT_ID, QUESTION_ID, OPERATION_TYPE)
        VALUES (:OLD.ANSWER_ID, :OLD.ATTEMPT_ID, :OLD.QUESTION_ID, 'DELETE');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_QUESTION_TOTALS_CT
FOR INSERT OR UPDATE OR DELETE ON QUESTION
COMPOUND TRIGGER
    TYPE T_ID_TAB IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
    G_QUIZ_IDS T_ID_TAB;
    G_COUNT PLS_INTEGER := 0;

    PROCEDURE ADD_ID(P_QUIZ_ID NUMBER) IS
        V_FOUND BOOLEAN := FALSE;
    BEGIN
        IF P_QUIZ_ID IS NULL THEN
            RETURN;
        END IF;

        FOR I IN 1 .. G_COUNT LOOP
            IF G_QUIZ_IDS(I) = P_QUIZ_ID THEN
                V_FOUND := TRUE;
                EXIT;
            END IF;
        END LOOP;

        IF NOT V_FOUND THEN
            G_COUNT := G_COUNT + 1;
            G_QUIZ_IDS(G_COUNT) := P_QUIZ_ID;
        END IF;
    END;

    AFTER EACH ROW IS
    BEGIN
        ADD_ID(NVL(:NEW.QUIZ_ID, :OLD.QUIZ_ID));
        IF UPDATING AND :OLD.QUIZ_ID <> :NEW.QUIZ_ID THEN
            ADD_ID(:OLD.QUIZ_ID);
            ADD_ID(:NEW.QUIZ_ID);
        END IF;
    END AFTER EACH ROW;

    AFTER STATEMENT IS
    BEGIN
        FOR I IN 1 .. G_COUNT LOOP
            UPDATE QUIZ
               SET TOTAL_MARKS = NVL((SELECT SUM(MARKS) FROM QUESTION WHERE QUIZ_ID = G_QUIZ_IDS(I)), 0)
             WHERE QUIZ_ID = G_QUIZ_IDS(I);
        END LOOP;
    END AFTER STATEMENT;
END;
/

PROMPT Creating attempt package...
CREATE OR REPLACE PACKAGE PKG_QUIZ_ATTEMPT AS
    FUNCTION START_ATTEMPT(
        P_QUIZ_ID     IN QUIZ_ATTEMPT.QUIZ_ID%TYPE,
        P_STUDENT_ID  IN QUIZ_ATTEMPT.STUDENT_ID%TYPE
    ) RETURN QUIZ_ATTEMPT.ATTEMPT_ID%TYPE;

    PROCEDURE AUTOSAVE_ANSWER(
        P_ATTEMPT_ID         IN QUIZ_ATTEMPT.ATTEMPT_ID%TYPE,
        P_QUESTION_ID        IN QUESTION.QUESTION_ID%TYPE,
        P_SELECTED_OPTION_ID IN QUESTION_OPTION.OPTION_ID%TYPE
    );

    PROCEDURE CLEAR_ANSWER(
        P_ATTEMPT_ID   IN QUIZ_ATTEMPT.ATTEMPT_ID%TYPE,
        P_QUESTION_ID  IN QUESTION.QUESTION_ID%TYPE
    );

    FUNCTION COMPUTE_ATTEMPT_SCORE(
        P_ATTEMPT_ID IN QUIZ_ATTEMPT.ATTEMPT_ID%TYPE
    ) RETURN NUMBER;

    PROCEDURE SUBMIT_ATTEMPT(
        P_ATTEMPT_ID IN QUIZ_ATTEMPT.ATTEMPT_ID%TYPE
    );
END PKG_QUIZ_ATTEMPT;
/

CREATE OR REPLACE PACKAGE BODY PKG_QUIZ_ATTEMPT AS
    PROCEDURE LOCK_ATTEMPT(
        P_ATTEMPT_ID IN QUIZ_ATTEMPT.ATTEMPT_ID%TYPE,
        P_QUIZ_ID    IN QUIZ.QUIZ_ID%TYPE DEFAULT NULL
    ) IS
        V_STATUS    QUIZ_ATTEMPT.STATUS%TYPE;
        V_QUIZ_ID   QUIZ_ATTEMPT.QUIZ_ID%TYPE;
        V_START     QUIZ_ATTEMPT.START_TIME%TYPE;
        V_DURATION  QUIZ.DURATION_MINUTES%TYPE;
    BEGIN
        SELECT QA.STATUS, QA.QUIZ_ID, QA.START_TIME, Q.DURATION_MINUTES
          INTO V_STATUS, V_QUIZ_ID, V_START, V_DURATION
          FROM QUIZ_ATTEMPT QA
          JOIN QUIZ Q ON Q.QUIZ_ID = QA.QUIZ_ID
         WHERE QA.ATTEMPT_ID = P_ATTEMPT_ID
         FOR UPDATE NOWAIT;

        IF P_QUIZ_ID IS NOT NULL AND V_QUIZ_ID <> P_QUIZ_ID THEN
            RAISE_APPLICATION_ERROR(-20101, 'Attempt does not belong to the expected quiz.');
        END IF;

        IF V_STATUS <> 'IN_PROGRESS' THEN
            RAISE_APPLICATION_ERROR(-20102, 'Attempt is no longer editable.');
        END IF;

        IF SYSDATE > (V_START + (V_DURATION / 1440)) THEN
            UPDATE QUIZ_ATTEMPT
               SET STATUS = 'AUTO_SUBMITTED',
                   SUBMISSION_TIME = SYSDATE,
                   TOTAL_SCORE = COMPUTE_ATTEMPT_SCORE(P_ATTEMPT_ID)
             WHERE ATTEMPT_ID = P_ATTEMPT_ID;

            RAISE_APPLICATION_ERROR(-20103, 'Quiz duration has expired. Attempt auto-submitted.');
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -54 THEN
                RAISE_APPLICATION_ERROR(-20104, 'Attempt is locked by another transaction.');
            ELSE
                RAISE;
            END IF;
    END;

    FUNCTION START_ATTEMPT(
        P_QUIZ_ID     IN QUIZ_ATTEMPT.QUIZ_ID%TYPE,
        P_STUDENT_ID  IN QUIZ_ATTEMPT.STUDENT_ID%TYPE
    ) RETURN QUIZ_ATTEMPT.ATTEMPT_ID%TYPE
    IS
        V_ATTEMPT_ID  QUIZ_ATTEMPT.ATTEMPT_ID%TYPE;
        V_STATUS      QUIZ_ATTEMPT.STATUS%TYPE;
    BEGIN
        BEGIN
            SELECT ATTEMPT_ID, STATUS
              INTO V_ATTEMPT_ID, V_STATUS
              FROM QUIZ_ATTEMPT
             WHERE QUIZ_ID = P_QUIZ_ID
               AND STUDENT_ID = P_STUDENT_ID
             FOR UPDATE NOWAIT;

            IF V_STATUS IN ('SUBMITTED', 'AUTO_SUBMITTED') THEN
                RAISE_APPLICATION_ERROR(-20105, 'Student already has a completed attempt for this quiz.');
            END IF;

            RETURN V_ATTEMPT_ID;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                INSERT INTO QUIZ_ATTEMPT (QUIZ_ID, STUDENT_ID, START_TIME, LAST_SAVED_AT, STATUS)
                VALUES (P_QUIZ_ID, P_STUDENT_ID, SYSDATE, SYSDATE, 'IN_PROGRESS')
                RETURNING ATTEMPT_ID INTO V_ATTEMPT_ID;

                RETURN V_ATTEMPT_ID;
            WHEN OTHERS THEN
                IF SQLCODE = -54 THEN
                    RAISE_APPLICATION_ERROR(-20106, 'Quiz attempt row is locked by another transaction.');
                ELSE
                    RAISE;
                END IF;
        END;
    END;

    PROCEDURE AUTOSAVE_ANSWER(
        P_ATTEMPT_ID         IN QUIZ_ATTEMPT.ATTEMPT_ID%TYPE,
        P_QUESTION_ID        IN QUESTION.QUESTION_ID%TYPE,
        P_SELECTED_OPTION_ID IN QUESTION_OPTION.OPTION_ID%TYPE
    ) IS
        V_QUIZ_ID    QUESTION.QUIZ_ID%TYPE;
        V_ANSWER_ID  STUDENT_ANSWER.ANSWER_ID%TYPE;
    BEGIN
        SELECT QUIZ_ID
          INTO V_QUIZ_ID
          FROM QUESTION
         WHERE QUESTION_ID = P_QUESTION_ID;

        LOCK_ATTEMPT(P_ATTEMPT_ID, V_QUIZ_ID);

        BEGIN
            SELECT ANSWER_ID
              INTO V_ANSWER_ID
              FROM STUDENT_ANSWER
             WHERE ATTEMPT_ID = P_ATTEMPT_ID
               AND QUESTION_ID = P_QUESTION_ID
             FOR UPDATE NOWAIT;

            UPDATE STUDENT_ANSWER
               SET SELECTED_OPTION_ID = P_SELECTED_OPTION_ID,
                   LAST_UPDATED_AT = SYSDATE
             WHERE ANSWER_ID = V_ANSWER_ID;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                INSERT INTO STUDENT_ANSWER (ATTEMPT_ID, QUESTION_ID, SELECTED_OPTION_ID)
                VALUES (P_ATTEMPT_ID, P_QUESTION_ID, P_SELECTED_OPTION_ID);
            WHEN OTHERS THEN
                IF SQLCODE = -54 THEN
                    RAISE_APPLICATION_ERROR(-20107, 'Answer row is locked by another transaction.');
                ELSE
                    RAISE;
                END IF;
        END;
    END;

    PROCEDURE CLEAR_ANSWER(
        P_ATTEMPT_ID   IN QUIZ_ATTEMPT.ATTEMPT_ID%TYPE,
        P_QUESTION_ID  IN QUESTION.QUESTION_ID%TYPE
    ) IS
        V_QUIZ_ID QUESTION.QUIZ_ID%TYPE;
    BEGIN
        SELECT QUIZ_ID
          INTO V_QUIZ_ID
          FROM QUESTION
         WHERE QUESTION_ID = P_QUESTION_ID;

        LOCK_ATTEMPT(P_ATTEMPT_ID, V_QUIZ_ID);

        DELETE FROM STUDENT_ANSWER
         WHERE ATTEMPT_ID = P_ATTEMPT_ID
           AND QUESTION_ID = P_QUESTION_ID;
    END;

    FUNCTION COMPUTE_ATTEMPT_SCORE(
        P_ATTEMPT_ID IN QUIZ_ATTEMPT.ATTEMPT_ID%TYPE
    ) RETURN NUMBER
    IS
        CURSOR C_ANSWERS IS
            SELECT SA.ANSWER_ID, SA.SELECTED_OPTION_ID, Q.MARKS
              FROM STUDENT_ANSWER SA
              JOIN QUESTION Q ON Q.QUESTION_ID = SA.QUESTION_ID
             WHERE SA.ATTEMPT_ID = P_ATTEMPT_ID;

        V_TOTAL NUMBER := 0;
        V_GAIN  NUMBER := 0;
    BEGIN
        FOR R IN C_ANSWERS LOOP
            V_GAIN := CASE
                WHEN FN_IS_CORRECT_OPTION(R.SELECTED_OPTION_ID) = 1 THEN R.MARKS
                ELSE 0
            END;

            UPDATE STUDENT_ANSWER
               SET IS_CORRECT = CASE WHEN V_GAIN > 0 THEN 'Y' ELSE 'N' END,
                   LAST_UPDATED_AT = SYSDATE
             WHERE ANSWER_ID = R.ANSWER_ID;

            V_TOTAL := V_TOTAL + V_GAIN;
        END LOOP;

        RETURN NVL(V_TOTAL, 0);
    END;

    PROCEDURE SUBMIT_ATTEMPT(
        P_ATTEMPT_ID IN QUIZ_ATTEMPT.ATTEMPT_ID%TYPE
    ) IS
        V_SCORE NUMBER;
    BEGIN
        LOCK_ATTEMPT(P_ATTEMPT_ID);
        V_SCORE := COMPUTE_ATTEMPT_SCORE(P_ATTEMPT_ID);

        UPDATE QUIZ_ATTEMPT
           SET STATUS = 'SUBMITTED',
               SUBMISSION_TIME = SYSDATE,
               TOTAL_SCORE = V_SCORE,
               LAST_SAVED_AT = SYSDATE
         WHERE ATTEMPT_ID = P_ATTEMPT_ID;
    END;
END PKG_QUIZ_ATTEMPT;
/

PROMPT Creating admin package...
CREATE OR REPLACE PACKAGE PKG_QUIZ_ADMIN AS
    PROCEDURE CREATE_SUBJECT(
        P_SUBJECT_NAME   IN SUBJECT.SUBJECT_NAME%TYPE,
        P_SUBJECT_CODE   IN SUBJECT.SUBJECT_CODE%TYPE,
        P_SEMESTER       IN SUBJECT.SEMESTER%TYPE,
        P_DEPARTMENT_ID  IN SUBJECT.DEPARTMENT_ID%TYPE,
        P_SUBJECT_ID     OUT SUBJECT.SUBJECT_ID%TYPE
    );

    PROCEDURE CREATE_QUIZ(
        P_QUIZ_TITLE         IN QUIZ.QUIZ_TITLE%TYPE,
        P_DURATION_MINUTES   IN QUIZ.DURATION_MINUTES%TYPE,
        P_QUIZ_DATE          IN QUIZ.QUIZ_DATE%TYPE,
        P_SUBJECT_ID         IN QUIZ.SUBJECT_ID%TYPE,
        P_CREATED_BY         IN QUIZ.CREATED_BY%TYPE,
        P_QUIZ_ID            OUT QUIZ.QUIZ_ID%TYPE
    );

    PROCEDURE ADD_QUESTION(
        P_QUIZ_ID         IN QUESTION.QUIZ_ID%TYPE,
        P_QUESTION_TEXT   IN QUESTION.QUESTION_TEXT%TYPE,
        P_MARKS           IN QUESTION.MARKS%TYPE,
        P_DISPLAY_ORDER   IN QUESTION.DISPLAY_ORDER%TYPE,
        P_QUESTION_ID     OUT QUESTION.QUESTION_ID%TYPE
    );

    PROCEDURE ADD_OPTION(
        P_QUESTION_ID     IN QUESTION_OPTION.QUESTION_ID%TYPE,
        P_OPTION_TEXT     IN QUESTION_OPTION.OPTION_TEXT%TYPE,
        P_IS_CORRECT      IN QUESTION_OPTION.IS_CORRECT%TYPE,
        P_DISPLAY_ORDER   IN QUESTION_OPTION.DISPLAY_ORDER%TYPE,
        P_OPTION_ID       OUT QUESTION_OPTION.OPTION_ID%TYPE
    );

    PROCEDURE RECOMPUTE_QUIZ_TOTALS(
        P_QUIZ_ID IN QUIZ.QUIZ_ID%TYPE
    );

    PROCEDURE PUBLISH_RESULTS(
        P_QUIZ_ID     IN QUIZ.QUIZ_ID%TYPE,
        P_TEACHER_ID  IN TEACHER.TEACHER_ID%TYPE
    );

    PROCEDURE UNPUBLISH_RESULTS(
        P_QUIZ_ID     IN QUIZ.QUIZ_ID%TYPE,
        P_TEACHER_ID  IN TEACHER.TEACHER_ID%TYPE
    );
END PKG_QUIZ_ADMIN;
/

CREATE OR REPLACE PACKAGE BODY PKG_QUIZ_ADMIN AS
    PROCEDURE VALIDATE_QUIZ_FOR_PUBLISH(
        P_QUIZ_ID IN QUIZ.QUIZ_ID%TYPE
    ) IS
        CURSOR C_Q IS
            SELECT QUESTION_ID
              FROM QUESTION
             WHERE QUIZ_ID = P_QUIZ_ID;

        V_OPTION_COUNT  NUMBER;
        V_CORRECT_COUNT NUMBER;
    BEGIN
        FOR R IN C_Q LOOP
            SELECT COUNT(*),
                   SUM(CASE WHEN IS_CORRECT = 'Y' THEN 1 ELSE 0 END)
              INTO V_OPTION_COUNT, V_CORRECT_COUNT
              FROM QUESTION_OPTION
             WHERE QUESTION_ID = R.QUESTION_ID;

            IF V_OPTION_COUNT < 2 THEN
                RAISE_APPLICATION_ERROR(-20201, 'Each question must have at least two options before publishing.');
            END IF;

            IF NVL(V_CORRECT_COUNT, 0) <> 1 THEN
                RAISE_APPLICATION_ERROR(-20202, 'Each question must have exactly one correct option.');
            END IF;
        END LOOP;
    END;

    PROCEDURE CREATE_SUBJECT(
        P_SUBJECT_NAME   IN SUBJECT.SUBJECT_NAME%TYPE,
        P_SUBJECT_CODE   IN SUBJECT.SUBJECT_CODE%TYPE,
        P_SEMESTER       IN SUBJECT.SEMESTER%TYPE,
        P_DEPARTMENT_ID  IN SUBJECT.DEPARTMENT_ID%TYPE,
        P_SUBJECT_ID     OUT SUBJECT.SUBJECT_ID%TYPE
    ) IS
    BEGIN
        INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_CODE, SEMESTER, DEPARTMENT_ID)
        VALUES (P_SUBJECT_NAME, UPPER(TRIM(P_SUBJECT_CODE)), P_SEMESTER, P_DEPARTMENT_ID)
        RETURNING SUBJECT_ID INTO P_SUBJECT_ID;
    END;

    PROCEDURE CREATE_QUIZ(
        P_QUIZ_TITLE         IN QUIZ.QUIZ_TITLE%TYPE,
        P_DURATION_MINUTES   IN QUIZ.DURATION_MINUTES%TYPE,
        P_QUIZ_DATE          IN QUIZ.QUIZ_DATE%TYPE,
        P_SUBJECT_ID         IN QUIZ.SUBJECT_ID%TYPE,
        P_CREATED_BY         IN QUIZ.CREATED_BY%TYPE,
        P_QUIZ_ID            OUT QUIZ.QUIZ_ID%TYPE
    ) IS
    BEGIN
        INSERT INTO QUIZ (QUIZ_TITLE, DURATION_MINUTES, QUIZ_DATE, SUBJECT_ID, CREATED_BY)
        VALUES (P_QUIZ_TITLE, P_DURATION_MINUTES, P_QUIZ_DATE, P_SUBJECT_ID, P_CREATED_BY)
        RETURNING QUIZ_ID INTO P_QUIZ_ID;
    END;

    PROCEDURE ADD_QUESTION(
        P_QUIZ_ID         IN QUESTION.QUIZ_ID%TYPE,
        P_QUESTION_TEXT   IN QUESTION.QUESTION_TEXT%TYPE,
        P_MARKS           IN QUESTION.MARKS%TYPE,
        P_DISPLAY_ORDER   IN QUESTION.DISPLAY_ORDER%TYPE,
        P_QUESTION_ID     OUT QUESTION.QUESTION_ID%TYPE
    ) IS
    BEGIN
        INSERT INTO QUESTION (QUIZ_ID, QUESTION_TEXT, MARKS, DISPLAY_ORDER)
        VALUES (P_QUIZ_ID, P_QUESTION_TEXT, P_MARKS, P_DISPLAY_ORDER)
        RETURNING QUESTION_ID INTO P_QUESTION_ID;
    END;

    PROCEDURE ADD_OPTION(
        P_QUESTION_ID     IN QUESTION_OPTION.QUESTION_ID%TYPE,
        P_OPTION_TEXT     IN QUESTION_OPTION.OPTION_TEXT%TYPE,
        P_IS_CORRECT      IN QUESTION_OPTION.IS_CORRECT%TYPE,
        P_DISPLAY_ORDER   IN QUESTION_OPTION.DISPLAY_ORDER%TYPE,
        P_OPTION_ID       OUT QUESTION_OPTION.OPTION_ID%TYPE
    ) IS
    BEGIN
        INSERT INTO QUESTION_OPTION (QUESTION_ID, OPTION_TEXT, IS_CORRECT, DISPLAY_ORDER)
        VALUES (P_QUESTION_ID, P_OPTION_TEXT, UPPER(TRIM(P_IS_CORRECT)), P_DISPLAY_ORDER)
        RETURNING OPTION_ID INTO P_OPTION_ID;
    END;

    PROCEDURE RECOMPUTE_QUIZ_TOTALS(
        P_QUIZ_ID IN QUIZ.QUIZ_ID%TYPE
    ) IS
    BEGIN
        UPDATE QUIZ
           SET TOTAL_MARKS = NVL((SELECT SUM(MARKS) FROM QUESTION WHERE QUIZ_ID = P_QUIZ_ID), 0)
         WHERE QUIZ_ID = P_QUIZ_ID;
    END;

    PROCEDURE PUBLISH_RESULTS(
        P_QUIZ_ID     IN QUIZ.QUIZ_ID%TYPE,
        P_TEACHER_ID  IN TEACHER.TEACHER_ID%TYPE
    ) IS
        CURSOR C_ATTEMPTS IS
            SELECT ATTEMPT_ID
              FROM QUIZ_ATTEMPT
             WHERE QUIZ_ID = P_QUIZ_ID
               AND STATUS IN ('SUBMITTED', 'AUTO_SUBMITTED')
             FOR UPDATE;

        V_OWNER_ID QUIZ.CREATED_BY%TYPE;
        V_SCORE    NUMBER;
    BEGIN
        SELECT CREATED_BY
          INTO V_OWNER_ID
          FROM QUIZ
         WHERE QUIZ_ID = P_QUIZ_ID
         FOR UPDATE;

        IF V_OWNER_ID <> P_TEACHER_ID THEN
            RAISE_APPLICATION_ERROR(-20203, 'Only the quiz creator can publish results.');
        END IF;

        VALIDATE_QUIZ_FOR_PUBLISH(P_QUIZ_ID);

        FOR R IN C_ATTEMPTS LOOP
            V_SCORE := PKG_QUIZ_ATTEMPT.COMPUTE_ATTEMPT_SCORE(R.ATTEMPT_ID);
            UPDATE QUIZ_ATTEMPT
               SET TOTAL_SCORE = V_SCORE
             WHERE CURRENT OF C_ATTEMPTS;
        END LOOP;

        UPDATE QUIZ
           SET RESULTS_PUBLISHED = 'Y'
         WHERE QUIZ_ID = P_QUIZ_ID;

        INSERT INTO RESULT_PUBLISH_LOG (QUIZ_ID, PUBLISHED_BY)
        VALUES (P_QUIZ_ID, P_TEACHER_ID);
    END;

    PROCEDURE UNPUBLISH_RESULTS(
        P_QUIZ_ID     IN QUIZ.QUIZ_ID%TYPE,
        P_TEACHER_ID  IN TEACHER.TEACHER_ID%TYPE
    ) IS
        V_OWNER_ID QUIZ.CREATED_BY%TYPE;
    BEGIN
        SELECT CREATED_BY
          INTO V_OWNER_ID
          FROM QUIZ
         WHERE QUIZ_ID = P_QUIZ_ID
         FOR UPDATE;

        IF V_OWNER_ID <> P_TEACHER_ID THEN
            RAISE_APPLICATION_ERROR(-20204, 'Only the quiz creator can unpublish results.');
        END IF;

        UPDATE QUIZ
           SET RESULTS_PUBLISHED = 'N'
         WHERE QUIZ_ID = P_QUIZ_ID;
    END;
END PKG_QUIZ_ADMIN;
/

PROMPT Creating views...
CREATE OR REPLACE VIEW VW_TEACHER_QUIZ_DASHBOARD AS
SELECT
    T.TEACHER_ID,
    T.NAME AS TEACHER_NAME,
    D.DEPARTMENT_NAME,
    S.SUBJECT_ID,
    S.SUBJECT_CODE,
    S.SUBJECT_NAME,
    Q.QUIZ_ID,
    Q.QUIZ_TITLE,
    Q.QUIZ_DATE,
    Q.DURATION_MINUTES,
    Q.TOTAL_MARKS,
    Q.RESULTS_PUBLISHED,
    COUNT(DISTINCT QQ.QUESTION_ID) AS QUESTION_COUNT,
    COUNT(DISTINCT QA.ATTEMPT_ID) AS ATTEMPT_COUNT,
    SUM(CASE WHEN QA.STATUS IN ('SUBMITTED', 'AUTO_SUBMITTED') THEN 1 ELSE 0 END) AS SUBMITTED_COUNT,
    ROUND(AVG(CASE WHEN QA.STATUS IN ('SUBMITTED', 'AUTO_SUBMITTED') THEN QA.TOTAL_SCORE END), 2) AS AVG_SCORE,
    MAX(CASE WHEN QA.STATUS IN ('SUBMITTED', 'AUTO_SUBMITTED') THEN QA.TOTAL_SCORE END) AS TOP_SCORE
FROM TEACHER T
JOIN DEPARTMENT D ON D.DEPARTMENT_ID = T.DEPARTMENT_ID
JOIN QUIZ Q ON Q.CREATED_BY = T.TEACHER_ID
JOIN SUBJECT S ON S.SUBJECT_ID = Q.SUBJECT_ID
LEFT JOIN QUESTION QQ ON QQ.QUIZ_ID = Q.QUIZ_ID
LEFT JOIN QUIZ_ATTEMPT QA ON QA.QUIZ_ID = Q.QUIZ_ID
GROUP BY
    T.TEACHER_ID, T.NAME, D.DEPARTMENT_NAME,
    S.SUBJECT_ID, S.SUBJECT_CODE, S.SUBJECT_NAME,
    Q.QUIZ_ID, Q.QUIZ_TITLE, Q.QUIZ_DATE, Q.DURATION_MINUTES,
    Q.TOTAL_MARKS, Q.RESULTS_PUBLISHED;

CREATE OR REPLACE VIEW VW_TEACHER_SUBMISSIONS AS
SELECT
    Q.CREATED_BY AS TEACHER_ID,
    QA.ATTEMPT_ID,
    QA.QUIZ_ID,
    Q.QUIZ_TITLE,
    QA.STUDENT_ID,
    ST.REGISTRATION_NO,
    ST.NAME AS STUDENT_NAME,
    QA.START_TIME,
    QA.LAST_SAVED_AT,
    QA.SUBMISSION_TIME,
    QA.STATUS,
    QA.TOTAL_SCORE,
    Q.TOTAL_MARKS,
    Q.RESULTS_PUBLISHED
FROM QUIZ_ATTEMPT QA
JOIN QUIZ Q ON Q.QUIZ_ID = QA.QUIZ_ID
JOIN STUDENT ST ON ST.STUDENT_ID = QA.STUDENT_ID;

CREATE OR REPLACE VIEW VW_STUDENT_PUBLISHED_RESULTS AS
SELECT
    QA.ATTEMPT_ID,
    ST.STUDENT_ID,
    ST.REGISTRATION_NO,
    ST.NAME AS STUDENT_NAME,
    Q.QUIZ_ID,
    Q.QUIZ_TITLE,
    S.SUBJECT_CODE,
    S.SUBJECT_NAME,
    QA.TOTAL_SCORE,
    Q.TOTAL_MARKS,
    ROUND((QA.TOTAL_SCORE / NULLIF(Q.TOTAL_MARKS, 0)) * 100, 2) AS PERCENTAGE,
    QA.SUBMISSION_TIME
FROM QUIZ_ATTEMPT QA
JOIN STUDENT ST ON ST.STUDENT_ID = QA.STUDENT_ID
JOIN QUIZ Q ON Q.QUIZ_ID = QA.QUIZ_ID
JOIN SUBJECT S ON S.SUBJECT_ID = Q.SUBJECT_ID
WHERE Q.RESULTS_PUBLISHED = 'Y'
  AND QA.STATUS IN ('SUBMITTED', 'AUTO_SUBMITTED');

PROMPT Inserting sample data...
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (10, 'COMPUTER SCIENCE');
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (20, 'INFORMATION TECHNOLOGY');

INSERT INTO TEACHER (TEACHER_ID, TEACHER_CODE, NAME, PASSWORD, DEPARTMENT_ID)
VALUES (101, 'CSE001', 'Anita Sharma', 'teach001', 10);
INSERT INTO TEACHER (TEACHER_ID, TEACHER_CODE, NAME, PASSWORD, DEPARTMENT_ID)
VALUES (102, 'ITE002', 'Rahul Menon', 'teach002', 20);

INSERT INTO STUDENT (STUDENT_ID, REGISTRATION_NO, NAME, PASSWORD, DEPARTMENT_ID)
VALUES (1001, '230100101', 'Aarav Nair', 'stud1001', 10);
INSERT INTO STUDENT (STUDENT_ID, REGISTRATION_NO, NAME, PASSWORD, DEPARTMENT_ID)
VALUES (1002, '230100102', 'Diya Rao', 'stud1002', 10);
INSERT INTO STUDENT (STUDENT_ID, REGISTRATION_NO, NAME, PASSWORD, DEPARTMENT_ID)
VALUES (1003, '230100103', 'Ishan Gupta', 'stud1003', 20);
INSERT INTO STUDENT (STUDENT_ID, REGISTRATION_NO, NAME, PASSWORD, DEPARTMENT_ID)
VALUES (1004, '230100104', 'Meera Pillai', 'stud1004', 10);
INSERT INTO STUDENT (STUDENT_ID, REGISTRATION_NO, NAME, PASSWORD, DEPARTMENT_ID)
VALUES (1005, '230100105', 'Rohan Das', 'stud1005', 20);

INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_CODE, SEMESTER, DEPARTMENT_ID)
VALUES (201, 'Database Systems', 'CSE2241', 4, 10);
INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_CODE, SEMESTER, DEPARTMENT_ID)
VALUES (202, 'Information Management', 'ITA2205', 4, 20);

INSERT INTO QUIZ (QUIZ_ID, QUIZ_TITLE, DURATION_MINUTES, TOTAL_MARKS, QUIZ_DATE, RESULTS_PUBLISHED, SUBJECT_ID, CREATED_BY)
VALUES (301, 'SQL Foundations Quiz', 30, 0, TO_DATE('2026-04-05 10:00', 'YYYY-MM-DD HH24:MI'), 'N', 201, 101);
INSERT INTO QUIZ (QUIZ_ID, QUIZ_TITLE, DURATION_MINUTES, TOTAL_MARKS, QUIZ_DATE, RESULTS_PUBLISHED, SUBJECT_ID, CREATED_BY)
VALUES (302, 'ER and Normalization Quiz', 25, 0, TO_DATE('2026-04-06 14:00', 'YYYY-MM-DD HH24:MI'), 'N', 202, 102);

INSERT INTO QUESTION (QUESTION_ID, QUESTION_TEXT, QUESTION_TYPE, MARKS, QUIZ_ID, DISPLAY_ORDER)
VALUES (401, 'Which SQL command is used to create a table?', 'SCQ', 2, 301, 1);
INSERT INTO QUESTION (QUESTION_ID, QUESTION_TEXT, QUESTION_TYPE, MARKS, QUIZ_ID, DISPLAY_ORDER)
VALUES (402, 'Which constraint prevents duplicate values in a column?', 'SCQ', 3, 301, 2);
INSERT INTO QUESTION (QUESTION_ID, QUESTION_TEXT, QUESTION_TYPE, MARKS, QUIZ_ID, DISPLAY_ORDER)
VALUES (403, 'Which statement is used to permanently save a transaction in Oracle?', 'SCQ', 3, 301, 3);

INSERT INTO QUESTION (QUESTION_ID, QUESTION_TEXT, QUESTION_TYPE, MARKS, QUIZ_ID, DISPLAY_ORDER)
VALUES (404, 'A relationship between SUBJECT and QUIZ in the ER diagram is best described as:', 'SCQ', 3, 302, 1);
INSERT INTO QUESTION (QUESTION_ID, QUESTION_TEXT, QUESTION_TYPE, MARKS, QUIZ_ID, DISPLAY_ORDER)
VALUES (405, 'Which normal form removes transitive dependency?', 'SCQ', 3, 302, 2);
INSERT INTO QUESTION (QUESTION_ID, QUESTION_TEXT, QUESTION_TYPE, MARKS, QUIZ_ID, DISPLAY_ORDER)
VALUES (406, 'Which SQL object is most suitable for a teacher dashboard summary?', 'SCQ', 4, 302, 3);

INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (501, 'CREATE TABLE', 'Y', 401, 1);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (502, 'ALTER TABLE', 'N', 401, 2);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (503, 'DROP TABLE', 'N', 401, 3);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (504, 'TRUNCATE TABLE', 'N', 401, 4);

INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (505, 'CHECK', 'N', 402, 1);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (506, 'UNIQUE', 'Y', 402, 2);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (507, 'DEFAULT', 'N', 402, 3);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (508, 'ORDER BY', 'N', 402, 4);

INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (509, 'ROLLBACK', 'N', 403, 1);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (510, 'SAVEPOINT', 'N', 403, 2);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (511, 'COMMIT', 'Y', 403, 3);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (512, 'FLASHBACK', 'N', 403, 4);

INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (513, 'One SUBJECT can contain many QUIZZES', 'Y', 404, 1);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (514, 'One QUIZ can contain many SUBJECTS', 'N', 404, 2);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (515, 'Each SUBJECT must have exactly one QUIZ', 'N', 404, 3);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (516, 'SUBJECT and QUIZ are unrelated', 'N', 404, 4);

INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (517, '1NF', 'N', 405, 1);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (518, '2NF', 'N', 405, 2);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (519, '3NF', 'Y', 405, 3);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (520, 'BCNF is lower than 3NF', 'N', 405, 4);

INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (521, 'SEQUENCE', 'N', 406, 1);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (522, 'VIEW', 'Y', 406, 2);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (523, 'SYNONYM', 'N', 406, 3);
INSERT INTO QUESTION_OPTION (OPTION_ID, OPTION_TEXT, IS_CORRECT, QUESTION_ID, DISPLAY_ORDER) VALUES (524, 'SAVEPOINT', 'N', 406, 4);

BEGIN
    PKG_QUIZ_ADMIN.RECOMPUTE_QUIZ_TOTALS(301);
    PKG_QUIZ_ADMIN.RECOMPUTE_QUIZ_TOTALS(302);
END;
/

PROMPT Creating sample attempts...
DECLARE
    V_ATTEMPT_ID NUMBER;
BEGIN
    V_ATTEMPT_ID := PKG_QUIZ_ATTEMPT.START_ATTEMPT(301, 1001);
    PKG_QUIZ_ATTEMPT.AUTOSAVE_ANSWER(V_ATTEMPT_ID, 401, 501);
    PKG_QUIZ_ATTEMPT.AUTOSAVE_ANSWER(V_ATTEMPT_ID, 402, 506);
    PKG_QUIZ_ATTEMPT.AUTOSAVE_ANSWER(V_ATTEMPT_ID, 403, 511);
    PKG_QUIZ_ATTEMPT.SUBMIT_ATTEMPT(V_ATTEMPT_ID);
END;
/

DECLARE
    V_ATTEMPT_ID NUMBER;
BEGIN
    V_ATTEMPT_ID := PKG_QUIZ_ATTEMPT.START_ATTEMPT(301, 1002);
    PKG_QUIZ_ATTEMPT.AUTOSAVE_ANSWER(V_ATTEMPT_ID, 401, 502);
    PKG_QUIZ_ATTEMPT.AUTOSAVE_ANSWER(V_ATTEMPT_ID, 402, 505);
END;
/

DECLARE
    V_ATTEMPT_ID NUMBER;
BEGIN
    V_ATTEMPT_ID := PKG_QUIZ_ATTEMPT.START_ATTEMPT(302, 1003);
    PKG_QUIZ_ATTEMPT.AUTOSAVE_ANSWER(V_ATTEMPT_ID, 404, 513);
    PKG_QUIZ_ATTEMPT.AUTOSAVE_ANSWER(V_ATTEMPT_ID, 405, 519);
    PKG_QUIZ_ATTEMPT.AUTOSAVE_ANSWER(V_ATTEMPT_ID, 406, 522);
    PKG_QUIZ_ATTEMPT.SUBMIT_ATTEMPT(V_ATTEMPT_ID);
END;
/

COMMIT;

PROMPT ============================================
PROMPT Setup complete
PROMPT Use: system / Hello123!
PROMPT ============================================
